### ISSUE TITLE
有HI3516CV500的ssd模型性能测试数据么

### ISSUE THREAD

**Issue by renfeier** [liqi-c/tengine-nnie#4]
用hisi官方提供的一些在cpu上计算的op耗时貌似很严重啊，作者是把cpu上的op用tengine里面的op算么，可是看测试代码里面似乎不是啊，有没有ssd模型的nnie op和cpu op耗时数据呢

**Comment by liqi-c** [comment]
有些模型的CPU上的前后处理op做了汇编优化，具体的要看代码,,,要看具体的硬件，这个demo可以测ssd的数据
