### ISSUE TITLE
请问这里使用的是不是开源版本的tengine？

### ISSUE THREAD

**Issue by chienkan** [liqi-c/tengine-nnie#5]
我看到README里面给的tengine下载链接是到官网去下载，那是不是意味着使用的是商业版本的tengine？

**Comment by liqi-c** [comment]
不是噢，是我们的评估版本。有些平台上是免费的



---原始邮件---
发件人: "chienkan"<notifications@github.com&gt;
发送时间: 2020年3月17日(周二) 晚上7:33
收件人: "liqi-c/tengine-nnie"<tengine-nnie@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [liqi-c/tengine-nnie] 请问这里使用的是不是开源版本的tengine？ (#5)




 
我看到README里面给的tengine下载链接是到官网去下载，那是不是意味着使用的是商业版本的tengine？

**Comment by chienkan** [comment]
明白了，多谢~

**Comment by yutao007** [comment]
您好，初次接触，您说的评估版是什么版本？网上看到三个版本：Github开源版本，Tengine Explore开发者版，及EAIDK版本。您方便给个资料连接吗？谢谢。

**Comment by liqi-c** [comment]
该版本要向OAL内部申请，您这边需要可以联系邮箱 Support@openailab.com , 说需要nnie的试用版本，说明芯片型号
